### ISSUE TITLE
请问本文章已经在TPDS上录用了吗？

### ISSUE THREAD

**Issue by 739982423** [icloud-ecnu/igniter#4]
非常感谢作者们提出的思路，给我们的工作带来了很大启发！
在涉及参考文献的部分，我们没有在TPDS上找到您的文章，所以无法引用。
请问作者该文章是否已经接收？可以上传arxiv吗

**Comment by 739982423** [comment]
Thank you very much for the idea of the author, which has brought great inspiration to our work!

In the section of reference, we could not find your article on TPDS, so we could not cite it. Could you please upload your article to arxiv？

**Comment by JBinin** [comment]
Thank you very much for your attention! We are glad that our work can help you. Our paper entered the third review last month and is expected to be accepted soon. After the article is accepted, we will update the README.md on GitHub as soon as possible. In addition, we have uploaded our paper to arxiv, and you can see it in a day or two.

**Comment by 739982423** [comment]
Okay, thank you very much!
